/**
 * Wires up click handlers for `.tabs` components embedded directly as raw
 * HTML inside a markdown content file (see
 * content/comparisons/02-syntax-side-by-side.md) — markdown supports raw
 * HTML passthrough, so the `.tabs`/`.tabs-nav`/`.tabs-panel` markup itself
 * is hand-authored in the .md source rather than generated by a new
 * marked renderer override; a `<script>` tag embedded in that same HTML
 * would never run (`innerHTML` never executes injected `<script>` tags),
 * so the click-handling logic lives here instead and is (re-)applied
 * after every page render, the same way mountAllLiveBlocks() is.
 */
export function mountAllTabs(root: ParentNode = document): void {
  const tabGroups = Array.from(root.querySelectorAll<HTMLElement>(".tabs"));
  for (const group of tabGroups) {
    const buttons = Array.from(group.querySelectorAll<HTMLButtonElement>(".tabs-nav button"));
    const panels = Array.from(group.querySelectorAll<HTMLElement>(".tabs-panel"));
    for (const button of buttons) {
      button.addEventListener("click", () => {
        const tab = button.dataset.tab;
        for (const b of buttons) b.classList.toggle("active", b === button);
        for (const p of panels) p.classList.toggle("active", p.dataset.tab === tab);
      });
    }
  }
}
